# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='testField',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
    ]
