# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20170327_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
