# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20170327_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seat',
            field=models.CommaSeparatedIntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
