# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20170327_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='data',
        ),
    ]
