# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_student_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
    ]
