# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='badges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='students',
            name='className',
            field=models.CharField(default='no Class', max_length=25),
        ),
        migrations.AddField(
            model_name='students',
            name='lastName',
            field=models.CharField(default='no Last Name', max_length=25),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='no Name', max_length=25),
        ),
        migrations.AddField(
            model_name='students',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentId',
            field=models.BigIntegerField(default='0'),
        ),
    ]
